apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kubernetes.io/part-of: sock-shop
    name: catalogue
  name: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      name: catalogue
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: catalogue
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
