apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kapicorp.dev/component: catalogue-db
    app.kubernetes.io/part-of: sock-shop
    name: catalogue-db
  name: catalogue-db
  namespace: sock-shop
spec:
  minReadySeconds:
  progressDeadlineSeconds:
  replicas: 1
  revisionHistoryLimit:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: sock-shop
      name: catalogue-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/part-of: sock-shop
        name: catalogue-db
    spec:
      affinity: {}
      containers:
        - args: []
          command: []
          env:
            - name: MYSQL_DATABASE
              value: socksdb
            - name: MYSQL_ROOT_PASSWORD
              value: i-navbnEcQdxu6kmpr6UVyO-hSm6JZYb0X98hTfkOdE
          image: weaveworksdemos/catalogue-db:0.3.0
          imagePullPolicy: IfNotPresent
          lifecycle: {}
          name: catalogue-db
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          resources: {}
          securityContext:
            readOnlyRootFilesystem: false
      dnsPolicy:
      hostNetwork:
      hostPID:
      imagePullSecrets: []
      initContainers: []
      nodeSelector: {}
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations: []
