apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: sock-shop
    name: frontend
  name: frontend
  namespace: sock-shop
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    name: frontend
  sessionAffinity: None
  type: LoadBalancer
