apiVersion: v1
kind: Service
metadata:
  labels:
    app.kapicorp.dev/component: orders-db
    app.kubernetes.io/part-of: sock-shop
    name: orders-db
  name: orders-db
  namespace: sock-shop
spec:
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: mongo
  selector:
    app.kubernetes.io/part-of: sock-shop
    name: orders-db
  sessionAffinity: None
  type: ClusterIP
