apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kapicorp.dev/component: session-db
    name: session-db
  name: session-db
  namespace: sock-shop
spec:
  minReadySeconds:
  progressDeadlineSeconds:
  replicas: 1
  revisionHistoryLimit:
  selector:
    matchLabels:
      name: session-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        name: session-db
    spec:
      affinity: {}
      containers:
        - args: []
          command: []
          image: redis:alpine
          imagePullPolicy: IfNotPresent
          lifecycle: {}
          name: session-db
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              add:
                - CHOWN
                - SETGID
                - SETUID
              drop:
                - all
      dnsPolicy:
      hostNetwork:
      hostPID:
      imagePullSecrets: []
      initContainers: []
      nodeSelector: {}
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations: []
