apiVersion: v1
kind: Service
metadata:
  labels:
    app.kapicorp.dev/component: user
    name: user
  name: user
  namespace: sock-shop
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    name: user
  sessionAffinity: None
  type: ClusterIP
