apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    name: guestbook-project
  name: guestbook-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
