apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    name: guestbook-app
  name: guestbook-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: guestbook-project
  source:
    path: guestbook
    plugin:
      env:
        - name: VAULT_ADDR
          value: https://vault.example.com
        - name: VAULT_TOKEN
          value: MyVaultToken
        - name: VAULT_CAPATH
          value: /etc/ssl/certs/example.root.crt
        - name: VAULT_SKIP_VERIFY
          value: 'True'
      name: kapitan
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
        - Validate=false
    targetRevision: master
