apiVersion: v1
kind: Secret
metadata:
  labels:
    name: repo-secret
  name: repo-secret
  namespace: argocd
stringData:
  insecure: 'true'
  password: mypsasword123
  type: git
  url: https://github.com/argoproj/argocd-example-apps.git
type: Opaque
