apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
    name: repo-my-repo-name
  name: repo-my-repo-name
  namespace: argocd
stringData:
  insecure: 'true'
  password: mypsasword123
  type: git
  url: https://github.com/argoproj/argocd-example-apps.git
type: Opaque
