classes:
  - kapitan.kube
  - kapitan.spinnaker
  - kapitan.generators.manifests
  - kapitan.generators.ingresses

parameters:
  scripts: []
  docs:
    - templates/docs/README.md 
  manifests: []
  kapitan:
    compile:
      - output_path: docs
        input_type: jinja2
        input_paths: ${docs}
      - output_path: scripts
        input_type: jinja2
        input_paths: ${scripts}
      - output_path: manifests
        input_type: jsonnet
        output_type: yaml
        input_paths: ${manifests}
      - output_path: pre-deploy
        input_type: jsonnet
        output_type: yaml
        input_paths:
          - components/pre-deploy/main.jsonnet
    vars:
      target: ${target_name}
