classes:
  - kapitan.kube
  - kapitan.spinnaker
  - kapitan.generators.manifests

parameters:
  scripts: []
  docs: []
  manifests: []
  kapitan:
    compile:
      - output_path: docs
        input_type: jinja2
        input_paths: ${docs}
      - output_path: scripts
        input_type: jinja2
        input_paths: ${scripts}
      - output_path: manifests
        input_type: jsonnet
        output_type: yaml
        input_paths: ${manifests}
    vars:
      target: ${target_name}
