---
parameters:
  generators:
    kubernetes:
      # Then namespace is already present in the actions-runner-controller.yaml
      ~namespace: {}

  # Download the github runner controller
  kapitan:
    dependencies:
      - type: https
        source: https://github.com/actions/actions-runner-controller/releases/download/v0.25.2/actions-runner-controller.yaml
        output_path: components/actions-runner-controller.yaml

    # Compiles and mutates some fields to setup service account
    compile:
      - output_path: manifests
        input_type: kadet
        output_type: yml
        prune: false
        input_params:
          files: [components/actions-runner-controller.yaml]
          mutations:
            bundle:
              - conditions:
                  # CRDs need to be setup separately
                  kind: [CustomResourceDefinition]
                filename: github-runners-crds
              - conditions:
                  kind: ['*']
                filename: github-runners-bundle
            patch:
              - conditions:
                  # Mutate the service account to use the github-runners-sa
                  kind: [CustomResourceDefinition]
                patch:
                  metadata:
                    annotations:
                      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Replace=true
        input_paths:
          - components/kstmz
