apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kapicorp.dev/component: tesoro
    name: tesoro
  name: tesoro
  namespace: tesoro
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kapicorp.dev/component: tesoro
    name: tesoro
  name: tesoro
  namespace: tesoro
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - events
      - secrets
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kapicorp.dev/component: tesoro
    name: tesoro
  name: tesoro
  namespace: tesoro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tesoro
subjects:
  - kind: ServiceAccount
    name: tesoro
    namespace: tesoro
