apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: artifactory
    chart: artifactory-11.7.6
    component: artifactory
    heritage: Tiller
    release: artifactory
  name: artifactory-artifactory
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: artifactory-artifactory
subjects:
  - kind: ServiceAccount
    name: artifactory-artifactory
