classes:
  - terraform.gcp.billing
  - terraform.gcp.services
  - terraform.local-state
  - terraform.gcp.gcs-bucket

parameters:
  resources:
    tf:
      resource:
        google_project_service:
          enable_container_service:
            service: container.googleapis.com
            project: \${google_project.project.project_id}
          enable_cloudresourcemanager_service:
            service: cloudresourcemanager.googleapis.com
            project: \${google_project.project.project_id}
          enable_serviceusage_service:
            service: serviceusage.googleapis.com
            project: \${google_project.project.project_id}