apiVersion: v1
kind: Service
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kapicorp.dev/component: carts
    app.kubernetes.io/part-of: sock-shop
    name: carts
  name: carts
  namespace: dev-sockshop
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/part-of: sock-shop
    name: carts
  sessionAffinity: None
  type: ClusterIP
