apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: sock-shop
    name: orders-db
  name: orders-db
  namespace: dev-sockshop
spec:
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: mongo
  selector:
    name: orders-db
  sessionAffinity: None
  type: ClusterIP
