apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kapicorp.dev/component: rabbit-mq
    app.kubernetes.io/part-of: sock-shop
    name: rabbit-mq
  name: rabbit-mq
  namespace: dev-sockshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/part-of: sock-shop
      name: rabbit-mq
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: sock-shop
        name: rabbit-mq
    spec:
      containers:
        - image: rabbitmq:3.6.8-management
          imagePullPolicy: IfNotPresent
          name: rabbit-mq
          ports:
            - containerPort: 15672
              name: management
              protocol: TCP
            - containerPort: 5672
              name: rabbitmq
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - CHOWN
                - SETGID
                - SETUID
                - DAC_OVERRIDE
              drop:
                - all
            readOnlyRootFilesystem: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
