apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kubernetes.io/part-of: sock-shop
    name: rabbit-mq
  name: rabbit-mq
spec:
  replicas: 2
  selector:
    matchLabels:
      name: rabbit-mq
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: rabbit-mq
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
