classes:
- kapitan.templates.kubernetes
parameters:
  gcp_project_id: kapitan-demo
  cluster: ${demo}
  demo:
    name: demo
    gcp_project_id: kapitan-demo
    zone: europe-west1-b
    type: gke
    cluster: demo
    id: gke_kapitan-demo_europe-west1-b_demo
    user: gke_kapitan-demo_europe-west1-b_demo
