# This class allows you to test the gkms backend.
# Once enabled, you should be able to use secrets like ?{gkms:my_secret_id||random:str}

#####################################################
# PLEASE NOTE THIS SHOULD ONLY BE USED FOR TESTING. #
#####################################################


parameters:
  kapitan:
    secrets:
      gkms:
        # Prerequisites: you need to use our provided DEMO service account
        # export GOOGLE_APPLICATION_CREDENTIALS=$PWD/resources/kapicorp-gmks-demo-service-account.json
        key: projects/kapicorp-gkms/locations/global/keyRings/kapitan-public/cryptoKeys/public