exclude: ^compiled/|^components/charts/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
        exclude:  |
            (?x)(
                ^Docs/|
            )
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: double-quote-string-fixer
    -   id: check-merge-conflict
