#!/bin/bash
set -o nounset -o pipefail -o noclobber -o errexit

DIR=$(dirname ${BASH_SOURCE[0]})
ABS_PATH=$(cd "${DIR}"; pwd)
KAPITAN_IMAGE=kapicorp/kapitan:v0.32.0

KAPITAN_BINARY="docker run --rm -i -u $UID --network host -w $PWD \
  -v $PWD:$PWD:delegated \
  $KAPITAN_IMAGE"

exec ${KAPITAN_BINARY} "$@"
