#!/bin/bash
set -o nounset -o pipefail -o noclobber -o errexit

DIR=$(dirname ${BASH_SOURCE[0]})
ABS_PATH=$(cd "${DIR}"; pwd)

KAPITAN_IMAGE=kapicorp/kapitan:v0.30.0-rc.0

KAPITAN_BINARY="docker run --rm -i -u $UID --network host -w /src \
 -v $PWD:/src:delegated \
 $KAPITAN_IMAGE"

exec ${KAPITAN_BINARY} "$@"
