parameters:

  pritunl:
    database:
      name: pritunl
      connection_string: mongodb://${pritunl:auth:username}:${pritunl:auth:password}@pritunl-mongo:27017/${pritunl:database:name}
    auth:
      username: pritunl
      password: ?{plain:targets/${target_name}/pritunl_password||random:str}

  components:
    pritunl:
      image: alledm/pritunl
      replicas: 1
      ports:
        http:
          service_port: 80
        vpn:
          service_port: 1194
        webui:
          service_port: 443
      healthcheck:
        readiness:
          type: HTTP
          scheme: HTTPS
          port: webui
          path: /
          timeout_seconds: 3
        liveness:
          type: HTTP
          scheme: HTTPS
          port: webui
          path: /
          timeout_seconds: 3
      service:
        type: LoadBalancer
      security_context:
        privileged: true
      config_maps:
        config:
          mount: /etc/pritunl.conf
          subPath: pritunl.conf
          data:
            pritunl.conf:
              value: |-
                {
                  "debug": false,
                  "bind_addr": "0.0.0.0",
                  "port": 443,
                  "log_path": "/var/log/pritunl.log",
                  "temp_path": "/tmp/pritunl_%r",
                  "local_address_interface": "auto",
                  "mongodb_uri": "${pritunl:database:connection_string}"
                }
