parameters:
  components:
    pritunl-mongo:
      type: statefulset
      image: mongo
      service:
        type: ClusterIP
      security_context:
        capabilities:
          drop:
            - all
          add:
            - CHOWN
            - SETGID
            - SETUID
      ports:
        mongo:
          service_port: 27017
      healthcheck:
        type: tcp
        port: mongo
        probes: ['readiness', 'liveness']
        timeout_seconds: 3
      volume_mounts:
        datadir:
          mountPath: /bitnami/mongodb
      volume_claims:
        datadir:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "standard"
            resources:
              requests: 
                storage: 10Gi
