parameters:
  components:
    pritunl-mongo:
      type: statefulset
      image: docker.io/bitnami/mongodb:4.2.6-debian-10-r23
      service:
        type: ClusterIP
      service_account:
        enabled: true
        create: true
      workload_security_context:
        fsGroup: 1001
      security_context:
        runAsNonRoot: true
        runAsUser: 1001
      ports:
        mongo:
          service_port: 27017
      env:
        MONGODB_ROOT_PASSWORD:
          secretKeyRef:
            key: mongodb-root-password
        MONGODB_ENABLE_IPV6: 'no'
        MONGODB_DISABLE_SYSTEM_LOG: 'no'
        MONGODB_SYSTEM_LOG_VERBOSITY: '0'
        MONGODB_ENABLE_DIRECTORY_PER_DB: 'no'
        MONGODB_USERNAME: ${pritunl:auth:username}
        MONGODB_PASSWORD: ${pritunl:auth:password}
        MONGODB_DATABASE: ${pritunl:database:name}
      healthcheck:
        readiness:
          type: command
          command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          timeout_seconds: 5
        liveness:
          type: command
          command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          timeout_seconds: 5
      volume_mounts:
        datadir:
          mountPath: /bitnami/mongodb
      volume_claims:
        datadir:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "standard"
            resources:
              requests:
                storage: 10Gi
      secrets:
        secrets:
          data:
            mongodb-root-password:
              value: ?{plain:targets/${target_name}/mongodb_password||randomstr|base64}
