#!/bin/bash
# generated with Kapitan

source $(dirname ${BASH_SOURCE[0]})/bash.include
setup_kubectl() {
  ${DIR}/setup_cluster >/dev/null
  ${DIR}/setup_context >/dev/null
}


KIND="kind"
$KIND create cluster -q --name kind || echo "Kind cluster kind already exists!"
$KIND export kubeconfig
