apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kubernetes.io/part-of: sock-shop
    name: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: frontend
    spec:
      affinity:
        podAntiAffinity: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
