apiVersion: v1
kind: Service
metadata:
  labels:
    name: shipping
  name: shipping
  namespace: prod-sockshop
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    name: shipping
  sessionAffinity: None
  type: ClusterIP
