apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kapicorp.dev/component: user-db
    name: user-db
  name: user-db
  namespace: prod-sockshop
spec:
  minReadySeconds:
  progressDeadlineSeconds:
  replicas: 1
  revisionHistoryLimit:
  selector:
    matchLabels:
      name: user-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        name: user-db
    spec:
      affinity: {}
      containers:
        - args: []
          command: []
          image: weaveworksdemos/user-db:0.3.0
          imagePullPolicy: IfNotPresent
          lifecycle: {}
          name: user-db
          ports:
            - containerPort: 27017
              name: mongo
              protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              add:
                - CHOWN
                - SETGID
                - SETUID
              drop:
                - all
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      dnsPolicy:
      hostNetwork:
      hostPID:
      imagePullSecrets: []
      initContainers: []
      nodeSelector: {}
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations: []
      volumes:
        - emptyDir:
            medium: Memory
          name: tmp-volume
