apiVersion: v1
kind: Service
metadata:
  labels:
    name: user-db
  name: user-db
  namespace: prod-sockshop
spec:
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: mongo
  selector:
    name: user-db
  sessionAffinity: None
  type: ClusterIP
