#!/bin/bash
# generated with Kapitan

source $(dirname ${BASH_SOURCE[0]})/bash.include


${KUBECTL_COMMAND} config set-context ${KUBECTL_CONTEXT} --cluster gke_kapitan-demo_europe-west1-b_demo --user gke_kapitan-demo_europe-west1-b_demo --namespace prod-sockshop