classes:
  - common
  - projects.kapitan-demo.kubernetes.demo
  - applications.sock-shop

parameters:
  components:
    frontend:
      service:
        type: NodePort
  ingresses:
    global:
      annotations:
        kubernetes.io/ingress.global-static-ip-name: sock-shop-prod
        networking.gke.io/managed-certificates: sockshop.kapicorp.com
      gke_managed_certificates: true
      domains:
      - sockshop.kapicorp.com
      default_backend:
        serviceName: frontend
        servicePort: 80
