parameters:
  kapitan:
    compile:
    - output_path: manifests
      input_type: kadet
      output_type: yml
      input_paths:
        - components/generators/kubernetes
    - output_path: docs
      input_type: kadet
      output_type: plain
      input_params:
        function: generate_docs
      input_paths:
        - components/generators/kubernetes

  generators:
    manifest:
      default_config:
        type: deployment
        service_account:
          create: false
        annotations:
          "manifests.kapicorp.com/generated": "true"