parameters:
  kapitan:
    compile:
    - output_path: terraform
      input_type: kadet
      output_type: json
      input_params:
        generator_root: resources.tf
      input_paths:
        - components/generators/terraform
    - input_type: copy
      ignore_missing: true
      input_paths:
        - resources/state/${target_name}/.terraform.lock.hcl
      output_path: terraform/