---
classes:
  - .common

parameters:
  terraform:
    resources:
      generic:
        google_project_service:
          compute:
            service: compute.googleapis.com
          storage-component:
            service: storage-component.googleapis.com
          container:
            service: container.googleapis.com
            depends_on:
              - google_project_service.compute
