apiVersion: v1
kind: Service
metadata:
  labels:
    app.kapicorp.dev/component: vault
    app.kubernetes.io/component: go
    app.kubernetes.io/version: 1.7.3
    name: vault-internal
  name: vault-internal
  namespace: vault
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8200
      protocol: TCP
      targetPort: http
    - name: http-rep
      protocol: TCP
      targetPort: http-rep
    - name: https-internal
      port: 8201
      protocol: TCP
      targetPort: https-internal
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: go
    app.kubernetes.io/version: 1.7.3
    name: vault
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kapicorp.dev/component: vault
    app.kubernetes.io/component: go
    app.kubernetes.io/version: 1.7.3
    name: vault-active
  name: vault-active
  namespace: vault
spec:
  ports:
    - name: http
      port: 8200
      protocol: TCP
      targetPort: http
    - name: http-rep
      protocol: TCP
      targetPort: http-rep
    - name: https-internal
      port: 8201
      protocol: TCP
      targetPort: https-internal
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: go
    app.kubernetes.io/version: 1.7.3
    name: vault
    vault-active: 'true'
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kapicorp.dev/component: vault
    app.kubernetes.io/component: go
    app.kubernetes.io/version: 1.7.3
    name: vault-standby
  name: vault-standby
  namespace: vault
spec:
  ports:
    - name: http
      port: 8200
      protocol: TCP
      targetPort: http
    - name: http-rep
      protocol: TCP
      targetPort: http-rep
    - name: https-internal
      port: 8201
      protocol: TCP
      targetPort: https-internal
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: go
    app.kubernetes.io/version: 1.7.3
    name: vault
    vault-active: 'false'
  sessionAffinity: None
  type: ClusterIP
