apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kubernetes.io/component: go
    app.kubernetes.io/version: 1.7.3
    name: vault
  name: vault
spec:
  replicas: 3
  selector:
    matchLabels:
      name: vault
  serviceName: vault-internal
  template:
    metadata:
      labels:
        name: vault
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - vault
                topologyKey: kubernetes.io/hostname
              weight: 1
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      serviceAccountName: vault
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: vault
          name: vault-config
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        labels:
          name: data
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: default
