apiVersion: v1
kind: Secret
metadata:
  labels:
    name: base64-as-base64
  name: base64-as-base64
  namespace: examples
stringData:
  CONNECTION: xyz://?{base64:eyJkYXRhIjogIlpERndRMWt3Y0c5VGEzQjJZV2M5UFE9PSIsICJlbmNvZGluZyI6ICJiYXNlNjQiLCAidHlwZSI6ICJiYXNlNjQifQ==:embedded}-someotherstuff
type: Opaque
