apiVersion: v1
data:
  logstash.yml: 'log.level: info

    queue.max_bytes: 4gb

    queue.type: persisted

    http.host: 0.0.0.0'
  pipelines.yml: "- pipeline.id: example\n  path.config: \"/usr/share/logstash/pipeline/example.conf\"\
    \n  pipeline.workers: 1\n  pipeline.batch.size: 200\n  queue.type: persisted"
kind: ConfigMap
metadata:
  labels:
    name: logstash-config
  name: logstash-config
  namespace: examples
---
apiVersion: v1
data:
  example.conf: "input { stdin { } }\n\nfilter {\n  grok {\n    match => { \"message\"\
    \ => \"%{COMBINEDAPACHELOG}\" }\n  }\n  date {\n    match => [ \"timestamp\" ,\
    \ \"dd/MMM/yyyy:HH:mm:ss Z\" ]\n  }\n}\n\noutput {\n  elasticsearch { hosts =>\
    \ [\"localhost:9200\"] }\n  stdout { codec => rubydebug }\n}"
kind: ConfigMap
metadata:
  labels:
    name: logstash-pipelines
  name: logstash-pipelines
  namespace: examples
