apiVersion: v1
data:
  example.conf: "input { stdin { } }\n\nfilter {\n  grok {\n    match => { \"message\"\
    \ => \"%{COMBINEDAPACHELOG}\" }\n  }\n  date {\n    match => [ \"timestamp\" ,\
    \ \"dd/MMM/yyyy:HH:mm:ss Z\" ]\n  }\n}\n\noutput {\n  elasticsearch { hosts =>\
    \ [\"localhost:9200\"] }\n  stdout { codec => rubydebug }\n}"
kind: ConfigMap
metadata:
  labels:
    name: logstash
  name: logstash-pipelines
  namespace: examples
