apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kapicorp.dev/component: trivy
    name: trivy
  name: trivy
  namespace: examples
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kapicorp.dev/component: trivy
    name: trivy
  name: trivy
  namespace: examples
rules:
  - apiGroups:
      - policy
    resourceNames:
      - trivy
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kapicorp.dev/component: trivy
    name: trivy
  name: trivy
  namespace: examples
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trivy
subjects:
  - kind: ServiceAccount
    name: trivy
    namespace: examples
