apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: go
    app.kubernetes.io/version: 0.18.1
    name: trivy
  name: trivy
  namespace: examples
spec:
  ports:
    - name: http
      port: 4954
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: go
    app.kubernetes.io/version: 0.18.1
    name: trivy
  sessionAffinity: None
  type: ClusterIP
