apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kapicorp.dev/component: trivy
    app.kubernetes.io/component: go
    app.kubernetes.io/version: 0.18.1
    name: trivy
  name: trivy
  namespace: examples
spec:
  minReadySeconds:
  progressDeadlineSeconds:
  replicas: 1
  revisionHistoryLimit:
  selector:
    matchLabels:
      app.kubernetes.io/component: go
      app.kubernetes.io/version: 0.18.1
      name: trivy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: go
        app.kubernetes.io/version: 0.18.1
        name: trivy
    spec:
      affinity: {}
      containers:
        - args:
            - server
          command: []
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: GITHUB_TOKEN
                  name: trivy
            - name: HTTPS_PROXY
              value: ''
            - name: HTTP_PROXY
              value: ''
            - name: NO_PROXY
              value: ''
            - name: TRIVY_CACHE_DIR
              value: /home/scanner/.cache/trivy
            - name: TRIVY_DEBUG
              value: 'False'
            - name: TRIVY_LISTEN
              value: 0.0.0.0:4954
            - name: TRIVY_SKIP_UPDATE
              value: 'False'
          image: docker.io/aquasec/trivy:0.18.1
          imagePullPolicy: IfNotPresent
          lifecycle: {}
          name: trivy
          ports:
            - containerPort: 4954
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
          securityContext: {}
          volumeMounts:
            - mountPath: /home/scanner/.cache
              name: data
              readOnly: false
            - mountPath: /tmp
              name: tmp-data
              readOnly: false
      dnsPolicy:
      hostNetwork:
      hostPID:
      imagePullSecrets: []
      initContainers: []
      nodeSelector: {}
      restartPolicy: Always
      securityContext: {}
      serviceAccountName: trivy
      terminationGracePeriodSeconds: 30
      tolerations: []
      volumes:
        - hostPath:
            path: /tmp/trivy
            type: DirectoryOrCreate
          name: data
        - emptyDir: {}
          name: tmp-data
        - name: trivy
          secret:
            defaultMode: 420
            items: []
            secretName: trivy
