apiVersion: v1
kind: Service
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kapicorp.dev/component: pritunl-mongo
    name: pritunl-mongo
  name: pritunl-mongo
  namespace: pritunl
spec:
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: mongo
  publishNotReadyAddresses:
  selector:
    name: pritunl-mongo
  sessionAffinity: None
  type: ClusterIP
