apiVersion: v1
kind: Service
metadata:
  labels:
    name: pritunl
  name: pritunl
  namespace: pritunl
spec:
  ports:
    - name: webui
      port: 443
      protocol: TCP
      targetPort: webui
  selector:
    name: pritunl
  sessionAffinity: None
  type: LoadBalancer
