apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kapicorp.dev/component: pritunl-mongo
    name: pritunl-mongo
  name: pritunl-mongo
  namespace: pritunl
