parameters:
  resources:
    tf:
      resource:
        google_project_service:
          enable_container_service:
            service: container.googleapis.com
            project: \${google_project.project.project_id}

        google_service_account:
          default:
            account_id: "gke-sa"
            display_name: Service Account for GKE
        
        google_container_cluster:
          primary:
            name: gke-cluster
            location: europe-west1
            initial_node_count: 1
            node_config:
              # Google recommends custom service accounts that have cloud-platform scope and permissions granted via IAM Roles.
              service_account: \${google_service_account.default.email}
              oauth_scopes: [
                "https://www.googleapis.com/auth/cloud-platform"
              ]
              labels:
                target: ${target_name}
            depends_on:
            - google_project_service.enable_container_service
            timeouts:
              create: "30m"
              update: "40m"