---
classes:
  - terraform.providers.google
  - terraform.remote-state
  - terraform.providers.gcp-impersonate

parameters:
  terraform_templates: []
  name: ${gcp_project_id}
  state_bucket_name: kapicorp-terraform-state
  scripts:
    - templates/scripts/terraform


  kapitan:
    labels:
      type: terraform

    compile:
      - output_path: terraform
        input_type: jinja2
        input_paths: ${terraform_templates}
