parameters:
  components:
    echo-server:
      application: microservices
      image: jmalloc/echo-server
      service:
        type: LoadBalancer
      healthcheck:
        type: http
        port: http
        probes: ['readiness']
        path: /_health
        timeout_seconds: 3
      ports:
        http:
          service_port: 80
          container_port: 8080
      config_maps:
        config:
          mount: /opt/echo-service
          data:
            echo-service.conf:
              template: 'components/echo-server/echo-server.conf.j2'
              values:
                example: true
