parameters:
  components:
    echo-server:
      application: microservices
      image: jmalloc/echo-server
      service:
        type: LoadBalancer
      healthcheck:
        liveness:
          type: http
          port: http
          path: /_health
          timeout_seconds: 3
        readiness:
          type: http
          port: http
          path: /_ready
          timeout_seconds: 5
      ports:
        http:
          service_port: 80
          container_port: 8080
        internal:
          container_port: 8081
      secrets:
        secret:
          data:
            encoded_secret:
              value: my_secret
              b64_encode: true
            better_secret:
              value: ?{base64:targets/${target_name}/password||randomstr|base64}

      config_maps:
        config:
          mount: /opt/echo-service
          items:
            - echo-service.conf
          data:
            echo-service.conf:
              template: "components/echo-server/echo-server.conf.j2"
              values:
                example: true
            simple_config:
              value: "not mounted"
      resources:
        requests:
          memory: 1G
          hugepages-2Mi: 80Mi
        limits:
          memory: 1G

  ingresses:
    global:
      paths:
        - backend:
            serviceName: echo-server
            servicePort: 80
          path: /echo/*
