parameters:
  service_accounts:
    gke-pvm-killer:
      ref: plain:targets/${target_name}/gke-pvm-killer-service-account
      secret: ?{plain:targets/${target_name}/gke-pvm-killer-service-account||randomstr}
      name: gke-pvm-killer@${google_project}.iam.gserviceaccount.com

  scripts:
    - templates/scripts/generate_sa_secrets.sh

  components:
    gke-pvm-killer:
      image: estafette/estafette-gke-preemptible-killer:1.2.5
      ports:
        liveness:
          service_port: 5000
        prom-metrics:
          service_port: 9001
      healthcheck:
        readiness:
          type: http
          port: liveness
          path: /liveness
          timeout_seconds: 3
        liveness:
          type: http
          port: liveness
          path: /liveness
          timeout_seconds: 3
      env:
        DRAIN_TIMEOUT: "300"
        INTERVAL: "600"
        GOOGLE_APPLICATION_CREDENTIALS: /opt/secrets/service_account_file
      secrets:
        secrets:
          mount: /opt/secrets
          items: ['service_account_file']
          data:
            service_account_file:
              value: ${service_accounts:gke-pvm-killer:secret}
