parameters:
  keda:
    params:
      # Variables to reference from other places
      application_version: 2.11.2
      service_account_name: keda-operator
      chart_name: keda
      chart_version: 2.11.2
      chart_dir: system/sources/charts/${keda:params:chart_name}/${keda:params:chart_name}/${keda:params:chart_version}/${keda:params:application_version}
      namespace: keda
      helm_values: {}

  kapitan:
    dependencies:
      # Tells kapitan to download the helm chart into the chart_dir directory
      - type: helm
        output_path: ${keda:params:chart_dir}
        source: https://kedacore.github.io/charts
        version: ${keda:params:chart_version}
        chart_name: ${keda:params:chart_name}


  charts:
     # Configures a helm generator to compile files for the given chart
    keda:
      chart_dir: ${keda:params:chart_dir}
      helm_params:
        namespace: ${keda:params:namespace}
        name: ${keda:params:chart_name}
      helm_values: ${keda:params:helm_values}
