parameters:
  mysql:
    settings:
      client:
        port: 3306
        socket: /var/run/mysqld/mysqld.sock
      mysqld:
        bind-address: 127.0.0.1
        max_allowed_packet: 64M
        thread_concurrency: 8        # Max CPU * 2
  components:
    mysql:
      type: statefulset
      image: mysql:5.7.28
      ports:
        mysql:
          service_port: 3306
      env:
        MYSQL_ROOT_PASSWORD:
          secretKeyRef:
            key: mysql-root-password
        MYSQL_PASSWORD:
          secretKeyRef:
            key: mysql-password
        MYSQL_USER: ""
        MYSQL_DATABASE: ""
      volume_mounts:
        datadir:
          mountPath: /var/lib/mysql
      volume_claims:
        datadir:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "standard"
            resources:
              requests:
                storage: 10Gi

      config_maps:
        config:
          mount: /etc/mysql/conf.d/
          data:
            mysql.cnf:
              value: |-
                ignore-db-dir=lost+found
            mytemplate.cnf:
              template: system/sources/templates/mysql/mytemplate.cnf.j2
              values:
                mysql: ${mysql:settings}


      secrets:
        secrets:
          versioned: true
          data:
            mysql-root-password:
              value: ?{plain:targets/${target_name}/mysql-root-password||random:str:32|base64}
            mysql-password:
              value: ?{plain:targets/${target_name}/mysql-password||random:str|base64}

