parameters:

  passwords:
    shared-password-string-data: ?{base64:targets/${target_name}/shared-password-string-data||random:str:10|base64}
    shared-password-base64-as-plain: ?{base64:targets/${target_name}/shared-password-base64-as-plain||random:str:15}
    shared-password-plain-as-base64: ?{plain:targets/${target_name}/shared-password-plain-as-base64||random:str:20|base64}
    shared-password-plain-as-plain-pass: ?{plain:targets/${target_name}/shared-password-plain-as-plain-pass||random:str:35}
  generators:
    kubernetes:
      secrets:
        base64-as-base64:
          string_data:
            CONNECTION:
              value: xyz://${passwords:shared-password-string-data}-someotherstuff
        base64-as-plain:
          string_data:
            CONNECTION:
              value: xyz://${passwords:shared-password-base64-as-plain}_someotherstuff
        plain-base64:
          string_data:
            CONNECTION:
              value: xyz://${passwords:shared-password-plain-as-base64}_xx_someotherstuff
        plain-plain-connection:
          string_data:
            CONNECTION:
              value: postgresql://myUser:${passwords:shared-password-plain-as-plain-pass}/database
        plain-plain-connection-b64:
          string_data:
            CONNECTION:
              b64_encode: true
              versioned: true
              value: postgresql://myUser:${passwords:shared-password-plain-as-plain-pass}/database
        plain-plain-connection-non-b64:
          string_data:
            CONNECTION:
              versioned: true
              b64_encode: false
              value: postgresql://myUser:${passwords:shared-password-plain-as-plain-pass}/database