parameters:
  generators:
    kubernetes:
      secrets:
        base64-as-base64:
          string_data:
            CONNECTION:
              value: xyz://?{base64:targets/${target_name}/shared-password-string-data||randomstr:10|base64}-someotherstuff
        base64-as-plain:
          string_data:
            CONNECTION:
              value: xyz://?{base64:targets/${target_name}/shared-password-base64-as-plain||randomstr:15}_someotherstuff
        plain-base64:
          string_data:
            CONNECTION:
              value: xyz://?{plain:targets/${target_name}/shared-password-plain-as-base64||randomstr:20|base64}_xx_someotherstuff
        plain-plain-connection:
          string_data:
            CONNECTION:
              value: postgresql://?{plain:targets/${target_name}/shared-password-plain-as-plain-user||randomstr:35}:?{plain:targets/${target_name}/shared-password-plain-as-plain-pass||randomstr:35}/database
        plain-plain-connection-b64:
          string_data:
            CONNECTION:
              b64_encode: true
              versioned: true
              value: postgresql://?{plain:targets/${target_name}/shared-password-plain-as-plain-user||randomstr:35}:?{plain:targets/${target_name}/shared-password-plain-as-plain-pass||randomstr:35}/database
        plain-plain-connection-non-b64:
          string_data:
            CONNECTION:
              versioned: true
              b64_encode: false
              value: postgresql://?{plain:targets/${target_name}/shared-password-plain-as-plain-user||randomstr:35}:?{plain:targets/${target_name}/shared-password-plain-as-plain-pass||randomstr:35}/database