parameters:
  trivy:
    image: docker.io/aquasec/trivy:0.18.1
    version: "0.18.1"
    component: go
    service:
      trivy:
        http_port: 4954
  pki:
    path: pki_int/sign/example-dot-com
    vault_address: https://vault.example.com:8200
    ca_bundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2akNDQTlLZ0F3SUJBZ0lRQ2pVSTFWd3BLd0Y5K0sxbHdBLzM1REFOQmdrcWhraUc5dzBCQVFzRkFEQmgKTVFzd0NRWURWUVFHRXdKVlV6RVZNQk1HQTFVRUNoTU1SR2xuYVVObGNuUWdTVzVqTVJrd0Z3WURWUVFMRXhCMwpkM2N1WkdsbmFXTmxjblF1WTI5dE1TQXdIZ1lEVlFRREV4ZEVhV2RwUTJWeWRDQkhiRzlpWVd3Z1VtOXZkQ0JEClFUQWVGdzB5TURBNU1qUXdNREF3TURCYUZ3MHpNREE1TWpNeU16VTVOVGxhTUU4eEN6QUpCZ05WQkFZVEFsVlQKTVJVd0V3WURWUVFLRXd4RWFXZHBRMlZ5ZENCSmJtTXhLVEFuQmdOVkJBTVRJRVJwWjJsRFpYSjBJRlJNVXlCUwpVMEVnVTBoQk1qVTJJREl3TWpBZ1EwRXhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDCkFRRUF3VXV6WlVkd3ZOMVBXTnZzbk8zRFp1VWZNUk5VclVwbVJoOHNDdXhrQitVdTNOeTVDaUR0MytQRTBKNmEKcVhvZGdvamxFVmJiSHA5WXdsSG5MRFFOTHRLUzRWYkw4WGxmczd1SHlpVURlNXBTUVdZUVlFOVhFMG53NkRkbgpnOS9uMDB0blRDSlJwdDhPbVJEdFYxRjBKdUo5eDhwaUxoTWJmeU9JSlZOdndUUllBSXVFLy9pK3AxaEpJbnVXCnJhS0lteFc4b0h6ZjZWR28xYkR0TitJMnRJSkxZclZKbXV6SFo5YmpQdlhqMWhKZVJQRy9jVUo5V0lRRGdMR0IKQWZyNXlqSzd0STRuaHlmRkszVFVxTmFYM3NOaytjck9VNkpXdkhnWGpra0RLYTc3U1Ura0Zibk84bHdaVjIxcgplYWNyb2ljZ0U3WFFQVURUSVRBSGsrcVo5UUlEQVFBQm80SUJyakNDQWFvd0hRWURWUjBPQkJZRUZMZHJvdXFvCnFvU01lZXEwMmcrWXNzV1Zkcm4wTUI4R0ExVWRJd1FZTUJhQUZBUGVVRFZXMFV5N1p2Q2o0aHNidzVleVBkRlYKTUE0R0ExVWREd0VCL3dRRUF3SUJoakFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJdwpFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBREIyQmdnckJnRUZCUWNCQVFScU1HZ3dKQVlJS3dZQkJRVUhNQUdHCkdHaDBkSEE2THk5dlkzTndMbVJwWjJsalpYSjBMbU52YlRCQUJnZ3JCZ0VGQlFjd0FvWTBhSFIwY0RvdkwyTmgKWTJWeWRITXVaR2xuYVdObGNuUXVZMjl0TDBScFoybERaWEowUjJ4dlltRnNVbTl2ZEVOQkxtTnlkREI3QmdOVgpIUjhFZERCeU1EZWdOYUF6aGpGb2RIUndPaTh2WTNKc015NWthV2RwWTJWeWRDNWpiMjB2UkdsbmFVTmxjblJICmJHOWlZV3hTYjI5MFEwRXVZM0pzTURlZ05hQXpoakZvZEhSd09pOHZZM0pzTkM1a2FXZHBZMlZ5ZEM1amIyMHYKUkdsbmFVTmxjblJIYkc5aVlXeFNiMjkwUTBFdVkzSnNNREFHQTFVZElBUXBNQ2N3QndZRlo0RU1BUUV3Q0FZRwpaNEVNQVFJQk1BZ0dCbWVCREFFQ0FqQUlCZ1puZ1F3QkFnTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSGVyCnQzb25QYTY3OW4vZ1dsYkpoS3JLVzNFWDNTSkgvRTZmN3REQnBBVGhvK3ZGU2NIOTBjbmZqSytVUlN4R0txTmoKT1NENW5rb2tsRUhJcWRuaW5GUUZCc3RjSEw0QUd3K29XdjhadTJYSEZxOGhWdDFoQmNucGo1aDIzMnNiMEhJTQpVTGt3S1hxL1lGa1FaaE02TGF3VkVXd3RJd3dDUGdVNy91V2huT0tLMjRmWFN1aGU1MGdHNjZzU212S3ZoTU5iCmcwcVpnWU9yQUtIS0NqeE1vaVdKS2lLbnBQTXpURnVNTGhvQ2x3K2RqMjB0bFFqN1Q5cnhrVGdsNFp4dVlSaUgKYXM2eHV3QXdhcHUzcjlyeHhaZitpbmdrcXVxVGdMb3paWHE4b1hmcGYya1VDd0EvZDVLeFRWdHpod29UMEp6SQo4a3M1VDFLRVNhWk1rRTRmOTdRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tC

  persistence:
    trivy:
      data:
        # storageclass: "${storageclass}"
        # accessModes: ["ReadWriteOnce"]
        # size: 100Gi
        # only used if hostPath is enabled below
        host_path: /tmp/trivy

  components:
    trivy:
      type: deployment
      image: ${trivy:image}
      imagePullPolicy: Always

      args:
        - server

      pod:
        labels:
          "app.kubernetes.io/running-on":
            fieldRef:
              fieldPath: spec.nodeName

      labels:
        app.kubernetes.io/version: ${trivy:version}
        app.kubernetes.io/component: ${trivy:component}

      env:
        TRIVY_LISTEN: "0.0.0.0:4954"
        TRIVY_CACHE_DIR: "/home/scanner/.cache/trivy"
        TRIVY_DEBUG: false
        TRIVY_SKIP_UPDATE: false
        GITHUB_TOKEN:
          secretKeyRef:
            name: trivy
            key: GITHUB_TOKEN
        HTTP_PROXY: ""
        HTTPS_PROXY: ""
        NO_PROXY: ""

      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 512Mi

      volume_mounts:
        data:
          mountPath: /home/scanner/.cache
          readOnly: false
        tmp-data:
          mountPath: /tmp
          readOnly: false

      volumes:
        data:
          # accessModes: ${persistence:trivy:data:accessModes}
          # storageClassName: ${persistence:trivy:data:storageclass}
          # resources:
          #   requests:
          #     storage: ${persistence:trivy:data:size}
          hostPath:
            path: ${persistence:trivy:data:host_path}
            type: DirectoryOrCreate
        tmp-data:
          emptyDir: {}

      service:
        type: ClusterIP
      ports:
        http:
          service_port: ${trivy:service:trivy:http_port}
          container_port: ${trivy:service:trivy:http_port}

      secrets:
        trivy:
          data:
            GITHUB_TOKEN:
              versioned: true
              b64_encode: true
              value: ""

      service_account:
        enabled: true
        create: true

      role:
        binding:
          subjects:
            - kind: ServiceAccount
              namespace: ${namespace}
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: Role
        rules:
        - apiGroups:
          - policy
          resources:
          - podsecuritypolicies
          verbs:
          - use
          resourceNames:
            - trivy

  generators:
    kubernetes:
      cert_manager:
          certs:
            cert:
              spec:
                secretName: my-cert-tls
                commonName: trivy.example.com
                dnsNames:
                  - trivy.example.com
                privateKey:
                  rotationPolicy: Always
                issuerRef:
                  name: trivy
                  kind: Issuer
                  group: cert-manager.io
          issuers:
            issuer:
              spec:
                vault:
                  path: ${pki:path}
                  server: ${pki:vault_address}
                  caBundle: ${pki:ca_bundle}
                  auth:
                    tokenSecretRef:
                      name: cert-manager-vault-token
                      key: token
