#!/bin/bash
# generated with Kapitan
source $(dirname ${BASH_SOURCE[0]})/bash.include


REFERENCE=${1? "Pass a reference as first argument: e.g. gkms:targets/kapicorp-project-123/reference_name"}
shift

set_reference ${REFERENCE} "$@"