apiVersion: v1
kind: Service
metadata:
  labels:
    app.kapicorp.dev/component: keda
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: keda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.11.2
    helm.sh/chart: keda-2.11.2
  name: keda-operator
  namespace: keda
spec:
  ports:
    - name: metricsservice
      port: 9666
      targetPort: 9666
  selector:
    app: keda-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keda-operator-metrics-apiserver
    app.kapicorp.dev/component: keda
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: keda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keda-operator-metrics-apiserver
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.11.2
    helm.sh/chart: keda-2.11.2
  name: keda-operator-metrics-apiserver
  namespace: keda
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: keda-operator-metrics-apiserver
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kapicorp.dev/component: keda
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: keda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keda-admission-webhooks
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.11.2
    helm.sh/chart: keda-2.11.2
  name: keda-admission-webhooks
  namespace: keda
spec:
  ports:
    - name: http
      port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: keda-admission-webhooks
