apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keda-operator
    app.kapicorp.dev/component: keda
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: keda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.11.2
    helm.sh/chart: keda-2.11.2
    name: keda-operator
  name: keda-operator
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-operator
  template:
    metadata:
      labels:
        app: keda-operator
        app.kubernetes.io/component: operator
        app.kubernetes.io/instance: keda
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: keda-operator
        app.kubernetes.io/part-of: keda-operator
        app.kubernetes.io/version: 2.11.2
        helm.sh/chart: keda-2.11.2
        name: keda-operator
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - --leader-elect
            - --zap-log-level=info
            - --zap-encoder=console
            - --zap-time-encoding=rfc3339
            - --cert-dir=/certs
            - --enable-cert-rotation=true
            - --cert-secret-name=kedaorg-certs
            - --operator-service-name=keda-operator
            - --metrics-server-service-name=keda-operator-metrics-apiserver
            - --webhooks-service-name=keda-admission-webhooks
          command:
            - /keda
          env:
            - name: WATCH_NAMESPACE
              value: ''
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: keda-operator
            - name: KEDA_HTTP_DEFAULT_TIMEOUT
              value: '3000'
            - name: KEDA_HTTP_MIN_TLS_VERSION
              value: TLS12
          image: ghcr.io/kedacore/keda:2.11.2
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 25
          name: keda-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 20
          resources:
            limits:
              cpu: 1
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /certs
              name: certificates
              readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: keda-operator
      volumes:
        - name: certificates
          secret:
            defaultMode: 420
            optional: true
            secretName: kedaorg-certs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keda-operator-metrics-apiserver
    app.kapicorp.dev/component: keda
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: keda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keda-operator-metrics-apiserver
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.11.2
    helm.sh/chart: keda-2.11.2
  name: keda-operator-metrics-apiserver
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-operator-metrics-apiserver
  template:
    metadata:
      labels:
        app: keda-operator-metrics-apiserver
        app.kubernetes.io/component: operator
        app.kubernetes.io/instance: keda
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: keda-operator-metrics-apiserver
        app.kubernetes.io/part-of: keda-operator
        app.kubernetes.io/version: 2.11.2
        helm.sh/chart: keda-2.11.2
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - /usr/local/bin/keda-adapter
            - --port=8080
            - --secure-port=6443
            - --logtostderr=true
            - --metrics-service-address=keda-operator.keda.svc.cluster.local:9666
            - --client-ca-file=/certs/ca.crt
            - --tls-cert-file=/certs/tls.crt
            - --tls-private-key-file=/certs/tls.key
            - --cert-dir=/certs
            - --v=0
          env:
            - name: WATCH_NAMESPACE
              value: ''
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KEDA_HTTP_DEFAULT_TIMEOUT
              value: '3000'
            - name: KEDA_HTTP_MIN_TLS_VERSION
              value: TLS12
          image: ghcr.io/kedacore/keda-metrics-apiserver:2.11.2
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6443
              scheme: HTTPS
            initialDelaySeconds: 5
          name: keda-operator-metrics-apiserver
          ports:
            - containerPort: 6443
              name: https
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 6443
              scheme: HTTPS
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: 1
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /certs
              name: certificates
              readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: false
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: keda-operator
      volumes:
        - name: certificates
          secret:
            defaultMode: 420
            secretName: kedaorg-certs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keda-admission-webhooks
    app.kapicorp.dev/component: keda
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: keda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keda-admission-webhooks
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.11.2
    helm.sh/chart: keda-2.11.2
    name: keda-admission-webhooks
  name: keda-admission-webhooks
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-admission-webhooks
  template:
    metadata:
      labels:
        app: keda-admission-webhooks
        app.kubernetes.io/component: operator
        app.kubernetes.io/instance: keda
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: keda-admission-webhooks
        app.kubernetes.io/part-of: keda-operator
        app.kubernetes.io/version: 2.11.2
        helm.sh/chart: keda-2.11.2
        name: keda-admission-webhooks
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - --zap-log-level=info
            - --zap-encoder=console
            - --zap-time-encoding=rfc3339
            - --cert-dir=/certs
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=:8080
          command:
            - /keda-admission-webhooks
          env:
            - name: WATCH_NAMESPACE
              value: ''
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: ghcr.io/kedacore/keda-admission-webhooks:2.11.2
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 25
          name: keda-admission-webhooks
          ports:
            - containerPort: 9443
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 20
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 10Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /certs
              name: certificates
              readOnly: true
      hostNetwork: false
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: keda-operator
      volumes:
        - name: certificates
          secret:
            defaultMode: 420
            secretName: kedaorg-certs
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    app.kapicorp.dev/component: keda
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: keda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: v1beta1.external.metrics.k8s.io
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.11.2
    helm.sh/chart: keda-2.11.2
  name: v1beta1.external.metrics.k8s.io
spec:
  group: external.metrics.k8s.io
  groupPriorityMinimum: 100
  service:
    name: keda-operator-metrics-apiserver
    namespace: keda
    port: 443
  version: v1beta1
  versionPriority: 100
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kapicorp.dev/component: keda
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: keda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keda-admission-webhooks
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.11.2
    helm.sh/chart: keda-2.11.2
  name: keda-admission
  namespace: keda
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: keda-admission-webhooks
        namespace: keda
        path: /validate-keda-sh-v1alpha1-scaledobject
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: vscaledobject.kb.io
    rules:
      - apiGroups:
          - keda.sh
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - scaledobjects
    sideEffects: None
    timeoutSeconds: 10
