apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kapicorp.dev/component: postgres-proxy
    name: postgres-proxy
    tier: db
  name: postgres-proxy
  namespace: postgres-proxy
spec:
  minAvailable: 2
  selector:
    matchLabels:
      name: postgres-proxy
      tier: db
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kapicorp.dev/component: postgres-proxy
    name: postgres-proxy
    tier: db
  name: postgres-proxy
  namespace: postgres-proxy
spec:
  resourcePolicy: {}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: postgres-proxy
  updatePolicy:
    updateMode: Auto
