apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres-proxy
    tier: db
  name: postgres-proxy
  namespace: postgres-proxy
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: postgresql
  selector:
    name: postgres-proxy
  sessionAffinity: None
  type: ClusterIP
