apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  labels:
    name: postgres-proxy
    tier: db
  name: postgres-proxy
  namespace: postgres-proxy
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: istio-proxy
        mode: 'Off'
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: postgres-proxy
  updatePolicy:
    updateMode: Auto
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    name: postgres-proxy
  name: postgres-proxy
  namespace: postgres-proxy
spec:
  minAvailable: 2
  selector:
    matchLabels:
      name: postgres-proxy
      tier: db
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    name: postgres-proxy
  name: postgres-proxy
  namespace: postgres-proxy
spec:
  minAvailable: 2
  selector:
    matchLabels:
      name: postgres-proxy
      tier: db
