# -------------------------------------------------
# Parameters
# -------------------------------------------------
parameters:
  rabbitmq-operator:
    chart_name: rabbitmq-cluster-operator
    chart_version: 2.6.1
    application_version: 1.12.1
    namespace: ${namespace}

    # https://artifacthub.io/packages/helm/bitnami/rabbitmq-cluster-operator
    # https://www.rabbitmq.com/kubernetes/operator/install-operator.html
    # https://www.rabbitmq.com/kubernetes/operator/using-operator.html
    # https://www.rabbitmq.com/kubernetes/operator/using-topology-operator.html
    # -------------------------------------------------
    # HELM VALUES
    # -------------------------------------------------
    helm_values:
      chart_name: rabbitmq-cluster-operator
      chart_version: ${rabbitmq-operator:chart_version}
      namespace: ${namespace}

  # -------------------------------------------------
  # HELM RENDER DEFINITION
  # -------------------------------------------------
  kapitan:
    dependencies:
    - type: helm
      output_path: components/charts/${rabbitmq-operator:chart_name}/${rabbitmq-operator:chart_version}/${rabbitmq-operator:application_version}
      source: https://charts.bitnami.com/bitnami
      version: ${rabbitmq-operator:chart_version}
      chart_name: ${rabbitmq-operator:chart_name}
    compile:
    - input_type: helm
      input_paths:
        - components/charts/${rabbitmq-operator:chart_name}/${rabbitmq-operator:chart_version}/${rabbitmq-operator:application_version}
      output_path: manifests
      helm_params:
        namespace: ${rabbitmq-operator:namespace}
        name: ${rabbitmq-operator:chart_name}
        output_file: ${rabbitmq-operator:chart_name}.yml
      helm_values: ${rabbitmq-operator:helm_values}