apiVersion: v1
kind: Service
metadata:
  labels:
    name: echo-server
  name: echo-server
  namespace: tutorial
spec:
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: nginx
  selector:
    name: echo-server
  sessionAffinity: None
  type: LoadBalancer
