apiVersion: v1
kind: Service
metadata:
  labels:
    name: echo-server
  name: echo-server
  namespace: tutorial
spec:
  ports:
    - name: http
      nodePort: 30001
      protocol: TCP
      targetPort: http
    - name: internal
      nodePort: 30002
      protocol: TCP
      targetPort: internal
    - name: nginx
      protocol: TCP
      targetPort: nginx
  selector:
    name: echo-server
  sessionAffinity: None
  type: NodePort
