apiVersion: v1
data:
  better_secret: ?{base64:targets/echo-server/password:ce03a7e0}
  encoded_secret: bXlfc2VjcmV0
kind: Secret
metadata:
  annotations:
    sealedsecrets.bitnami.com/managed: 'true'
  labels:
    name: echo-server
  name: echo-server
  namespace: echo-server
type: Opaque
