
# -------------------------------------------------
# Parameters
# -------------------------------------------------
parameters:
  argocd:

    # -------------------------------------------------
    # HELM VALUES
    # -------------------------------------------------
    helm_values:
      server:
        # -------------------------------------------------
        # Container args
        # -------------------------------------------------
        extraArgs:
          - --insecure

        # -------------------------------------------------
        # AutoScaling
        # -------------------------------------------------
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 2

        # -------------------------------------------------
        # Logging
        # -------------------------------------------------
        logFormat: json

        # -------------------------------------------------
        # Security
        # -------------------------------------------------
        containerSecurityContext:
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true

        # -------------------------------------------------
        # Resources
        # -------------------------------------------------
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi

        # -------------------------------------------------
        # Certificate
        # -------------------------------------------------
        certificate:
          enabled: false
          domain: ${argocd:external_url}
          issuer:
            kind: ClusterIssuer
            name: letsencrypt-prod

        # -------------------------------------------------
        # Monitoring
        # -------------------------------------------------
        metrics:
          enabled: true

        # -------------------------------------------------
        # Ingress
        # -------------------------------------------------
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: true
            cert-manager.io/cluster-issuer: letsencrypt-prod
          labels: {}
          hosts:
            - ${argocd:external_url}
          https: false
          tls:
            - secretName: argocd-server-tls
              hosts:
                - ${argocd:external_url}

        # -------------------------------------------------
        # Additional resources
        # -------------------------------------------------
        volumes:
          - name: selfsigned-certs
            emptyDir: {}
        volumeMounts:
          - name: selfsigned-certs
            mountPath: /etc/ssl/certs/example.root.crt
            subPath: example.root.crt
        initContainers:
          - name: selfsigned-certs
            image: ${argocd:tools:selfsigned-certs:image}
            command: [sh, -c]
            args:
              - wget --quiet --no-check-certificate https://vault.example.com/v1/example_certs/ca/pem -O /selfsigned-certs/example.root.crt
            volumeMounts:
              - mountPath: /selfsigned-certs
                name: selfsigned-certs
