# -------------------------------------------------
# Parameters
# -------------------------------------------------
parameters:
  argocd:

    # -------------------------------------------------
    # HELM VALUES
    # -------------------------------------------------
    helm_values:
      controller:

        # -------------------------------------------------
        # Container
        # -------------------------------------------------
        replicas: 2
        enableStatefulSet: false

        # -------------------------------------------------
        # Logging
        # -------------------------------------------------
        logFormat: json

        # -------------------------------------------------
        # Security
        # -------------------------------------------------
        containerSecurityContext:
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true

        # -------------------------------------------------
        # Resources
        # -------------------------------------------------
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi

        # -------------------------------------------------
        # Monitoring
        # -------------------------------------------------
        metrics:
          enabled: true

        # -------------------------------------------------
        # Additional resources
        # -------------------------------------------------
        volumes:
          - name: selfsigned-certs
            emptyDir: {}
        volumeMounts:
          - name: selfsigned-certs
            mountPath: /etc/ssl/certs/example.root.crt
            subPath: example.root.crt
        initContainers:
          - name: selfsigned-certs
            image: ${argocd:tools:selfsigned-certs:image}
            command: [sh, -c]
            args:
              - wget --quiet --no-check-certificate https://vault.example.com:8200/v1/example_certs/ca/pem -O /selfsigned-certs/example.root.crt
            volumeMounts:
              - mountPath: /selfsigned-certs
                name: selfsigned-certs