# -------------------------------------------------
# Parameters
# -------------------------------------------------
parameters:
  argocd:

    # -------------------------------------------------
    # HELM VALUES
    # -------------------------------------------------
    helm_values:
      dex:
        enabled: true
        name: dex-server

        # -------------------------------------------------
        # Container
        # -------------------------------------------------
        enableStatefulSet: false

        # -------------------------------------------------
        # Monitoring
        # -------------------------------------------------
        metrics:
          enabled: true

        # -------------------------------------------------
        # Logging
        # -------------------------------------------------
        logFormat: json

        # -------------------------------------------------
        # Security
        # -------------------------------------------------
        containerSecurityContext:
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true

        # -------------------------------------------------
        # Resources
        # -------------------------------------------------
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi