
# -------------------------------------------------
# Parameters
# -------------------------------------------------
parameters:
  argocd:

    # -------------------------------------------------
    # HELM VALUES
    # -------------------------------------------------
    helm_values:
      server:
        #
        # OIDC
        #
        configEnabled: true
        config:
          oidc.config: |
            name: AzureAD
            issuer: https://login.microsoftonline.com/TENANT_ID/v2.0
            clientID: CLIENT_ID
            clientSecret: $oidc.azuread.clientSecret
            requestedIDTokenClaims:
              groups:
                essential: true
            requestedScopes:
              - openid
              - profile
              - email
