parameters:
  components:
    carts-db:
      application: sock-shop
      image: mongo
      service:
        type: ClusterIP
      ports:
        mongo:
          service_port: 27017
      volume_mounts:
        tmp-volume:
          mountPath: /tmp
      volumes:
        tmp-volume:
          emptyDir:
            medium: Memory
