parameters:
  components:
    frontend:
      application: sock-shop
      image: weaveworksdemos/front-end:0.3.12
      service:
        type: LoadBalancer
      ports:
        http:
          service_port: 80
          container_port: 8079
      security_context:
        runAsNonRoot: true
        runAsUser: 10001
        capabilities:
          drop:
            - all
      healthcheck:
        readiness:
          type: HTTP
          port: http
          path: /
          timeout_seconds: 3
        liveness:
          type: HTTP
          port: http
          path: /
          timeout_seconds: 5
      env:
        SESSION_REDIS: 'true'
