parameters:
  components:
    payment:
      application: sock-shop
      image: weaveworksdemos/payment:0.4.3
      service:
        type: ClusterIP
      ports:
        http:
          service_port: 80
      security_context:
        runAsNonRoot: true
        runAsUser: 10001
        capabilities:
          drop:
            - all
          add:
            - NET_BIND_SERVICE
      healthcheck:
        readiness:
          type: HTTP
          port: http
          path: /health
          timeout_seconds: 3
        liveness:
          type: HTTP
          port: http
          path: /health
          timeout_seconds: 5
