parameters:
  components:
    queue-master:
      application: sock-shop
      image: weaveworksdemos/queue-master:0.3.1
      service:
        type: ClusterIP
      ports:
        http:
          service_port: 80
      healthcheck:
        readiness:
          type: http
          port: http
          path: /health
          timeout_seconds: 3
        liveness:
          type: http
          port: http
          path: /health
          timeout_seconds: 5
      env:
        ZIPKIN: zipkin.jaeger.svc.cluster.local
        JAVA_OPTS: "-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom"
      volume_mounts:
        tmp-volume:
          mountPath: /tmp
      volumes:
        tmp-volume:
          emptyDir:
            medium: Memory
