parameters:
  components:
    session-db:
      image: redis:alpine
      service:
        type: ClusterIP
      ports:
        redis:
          service_port: 6379
      security_context:
        capabilities:
          drop:
            - all
          add:
            - CHOWN
            - SETGID
            - SETUID
