parameters:
  components:
    shipping:
      image: weaveworksdemos/shipping:0.4.8
      service:
        type: ClusterIP
      ports:
        http:
          service_port: 80
      security_context:
        runAsNonRoot: true
        runAsUser: 10001
        capabilities:
          drop:
            - all
          add:
            - NET_BIND_SERVICE
      healthcheck:
        readiness:
          type: http
          port: http
          path: /health
          timeout_seconds: 3
          initial_delay_seconds: 120
        liveness:
          type: http
          port: http
          path: /health
          timeout_seconds: 5
      env:
        ZIPKIN: zipkin.jaeger.svc.cluster.local
        JAVA_OPTS: "-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom"
      volume_mounts:
        tmp-volume:
          mountPath: /tmp
      volumes:
        tmp-volume:
          emptyDir:
            medium: Memory
