parameters:
  components:
    user-db:
      image: weaveworksdemos/user-db:0.3.0
      service:
        type: ClusterIP
      ports:
        mongo:
          service_port: 27017
      security_context:
        capabilities:
          drop:
            - all
          add:
            - CHOWN
            - SETGID
            - SETUID
      volume_mounts:
        tmp-volume:
          mountPath: /tmp
      volumes:
        tmp-volume:
          emptyDir:
            medium: Memory
