parameters:
  components:
    user:
      image: weaveworksdemos/user:0.4.7
      service:
        type: ClusterIP
      ports:
        http:
          service_port: 80
      env:
        mongo: "user-db:27017"
      healthcheck:
        type: http
        port: http
        probes: ['readiness', 'liveness']
        path: /health
        timeout_seconds: 3
      env:
        ZIPKIN: zipkin.jaeger.svc.cluster.local
        JAVA_OPTS: "-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom"
      volume_mounts:
        tmp-volume:
          mountPath: /tmp
      volumes:
        tmp-volume:
          emptyDir:
            medium: Memory
