parameters:
  components:
    user:
      image: weaveworksdemos/user:0.4.7
      service:
        type: ClusterIP
      ports:
        http:
          service_port: 80
      env:
        mongo: "user-db:27017"
      security_context:
        capabilities:
          drop:
            - all
          add:
            - NET_BIND_SERVICE
        runAsNonRoot: true
        runAsUser: 10001
      healthcheck:
        type: http
        port: http
        probes: ['readiness', 'liveness']
        path: /health
        timeout_seconds: 3
      volume_mounts:
        tmp-volume:
          mountPath: /tmp
      volumes:
        tmp-volume:
          emptyDir:
            medium: Memory
