# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single jb called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

# Disable because it's not working
#    - name: Kapitan compile
#      uses: ademariag/kapitan/kapitan-compile-action@v1
